# 应用服务 WEB 访问端口
#server:
#  port: 10000
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hxmall_ums
#    password: root
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#  application:
#    name: hxmallShopMember
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
##spring:
##  cloud:
##    nacos:
##      server-addr: 127.0.0.1:8848
##  application:
##    name: hxmallShopMember
#
#member:
#  user:
#    name: haha
#    password: 123456